"""Tests for opening the draft PR (issue #16).

GitHub is mocked, so these assert the trust contract without any network: the
open-PR action is a greylist action that is queued for approval and only ever
executed through the dry-run-by-default gate; the PR is a draft, linked to the
issue, and labeled AI-generated; and an off-target repo can't even be queued.
"""

from __future__ import annotations

from datetime import UTC, datetime

import pytest

from steward.config import Settings
from steward.fix.draft_pr import (
    AI_GENERATED_LABEL,
    DraftPullRequestOpener,
    PullRequestRef,
    branch_name,
    render_pr_body,
)
from steward.graph.state import GraphState, OpenedPR, ProposedPatch, ReproOutcome, ReproVerdict
from steward.policy.approvals import ApprovalError, ApprovalQueue
from steward.policy.audit import InMemoryAuditLog
from steward.policy.engine import Action, ActionKind, PolicyEngine
from steward.policy.execute import ExecutionGate
from steward.sandbox import SandboxResult
from steward.triage.models import IssueState, NormalizedIssue

TARGET = "stewardbot/demo-shop"


class MockGitHub:
    def __init__(self) -> None:
        self.created: dict[str, str] | None = None
        self.labeled: dict[str, object] | None = None

    def create_draft_pull_request(
        self, *, repo: str, head: str, base: str, title: str, body: str
    ) -> PullRequestRef:
        self.created = {"repo": repo, "head": head, "base": base, "title": title, "body": body}
        return PullRequestRef(number=42, url=f"https://github.com/{repo}/pull/42")

    def add_labels(self, *, repo: str, number: int, labels: list[str]) -> None:
        self.labeled = {"repo": repo, "number": number, "labels": labels}


def _settings(**env: str) -> Settings:
    base = {"STEWARD_GITHUB_REPO": TARGET}
    base.update(env)
    return Settings(_env_file=None, **base)  # type: ignore[call-arg]


def _state() -> GraphState:
    now = datetime(2026, 6, 15, tzinfo=UTC)
    issue = NormalizedIssue(
        number=128,
        title="Checkout total ignores discount code",
        body="Applying a code does not reduce the total.",
        state=IssueState.OPEN,
        created_at=now,
        updated_at=now,
    )
    result = SandboxResult(
        passed=True,
        exit_code=0,
        timed_out=False,
        duration_s=1.23,
        stdout="1 passed",
        stderr="",
        image="python:3.12-slim",
        command="python -m unittest",
    )
    return GraphState(
        issue=issue,
        trace_id="trace-xyz",
        hypothesis="discount not applied before total",
        patch=ProposedPatch(diff="--- a\n+++ b", proof_test="t", proof_test_path="test_proof.py"),
        repro=ReproOutcome(verdict=ReproVerdict.REPRODUCED, summary="total unchanged with code"),
        test_result=result,
        verified=True,
    )


def _opener(
    settings: Settings, github: MockGitHub
) -> tuple[DraftPullRequestOpener, ApprovalQueue, InMemoryAuditLog]:
    audit = InMemoryAuditLog()
    engine = PolicyEngine(target_repo=TARGET)
    queue = ApprovalQueue(audit_log=audit)
    gate = ExecutionGate(settings=settings, audit_log=audit)
    opener = DraftPullRequestOpener(engine=engine, queue=queue, gate=gate, github=github)
    return opener, queue, audit


def test_branch_name_is_conventional() -> None:
    assert branch_name(128, "Checkout total ignores discount code").startswith(
        "fix/issue-128-checkout-total-ignores-discount"
    )
    assert branch_name(9, "!!!") == "fix/issue-9"


def test_pr_body_links_labels_and_grounds() -> None:
    body = render_pr_body(_state())
    assert "Closes #128" in body
    assert "generated by Steward" in body
    assert "test_proof.py" in body
    assert "passed after the" in body  # proof evidence
    assert "trace-xyz" in body


def test_open_draft_queues_for_approval_without_touching_github() -> None:
    github = MockGitHub()
    opener, queue, audit = _opener(_settings(), github)

    planned = opener.open_draft(_state())

    assert isinstance(planned, OpenedPR)
    assert planned.draft is True
    assert planned.number is None  # proposed, not yet opened
    assert planned.branch.startswith("fix/issue-128-")
    # Queued as a greylist action awaiting a human; GitHub untouched.
    pending = queue.pending()
    assert len(pending) == 1
    assert pending[0].action.kind is ActionKind.OPEN_DRAFT_PR
    assert github.created is None
    assert any("approval requested" in (r.note or "") for r in audit.records())


def test_execute_live_opens_draft_and_labels_ai_generated() -> None:
    github = MockGitHub()
    opener, queue, _ = _opener(
        _settings(STEWARD_DRY_RUN="false", STEWARD_LIVE_ACTIONS="open_draft_pr"), github
    )
    opener.open_draft(_state())
    approved = queue.approve(queue.pending()[0].approval_id, by="maintainer")

    pr = opener.execute_approved(approved, trace_id="trace-xyz")

    assert pr.number == 42
    assert pr.draft is True
    assert github.created is not None
    assert github.created["base"] == "main"
    assert github.created["head"].startswith("fix/issue-128-")
    assert "Closes #128" in github.created["body"]
    assert github.labeled == {
        "repo": TARGET,
        "number": 42,
        "labels": [AI_GENERATED_LABEL],
    }


def test_dry_run_default_does_not_touch_github() -> None:
    github = MockGitHub()
    opener, queue, audit = _opener(_settings(), github)  # dry_run defaults to True
    opener.open_draft(_state())
    approved = queue.approve(queue.pending()[0].approval_id, by="maintainer")

    pr = opener.execute_approved(approved, trace_id="trace-xyz")

    assert pr.number is None  # nothing opened
    assert github.created is None
    assert github.labeled is None
    assert any("dry-run" in (r.note or "") for r in audit.records())


def test_off_target_repo_cannot_even_be_queued() -> None:
    # Steward never targets a repo it doesn't own: a deny verdict can't be queued.
    audit = InMemoryAuditLog()
    engine = PolicyEngine(target_repo=TARGET)
    queue = ApprovalQueue(audit_log=audit)
    foreign = Action(
        kind=ActionKind.OPEN_DRAFT_PR,
        repo="someone-else/their-repo",
        summary="open PR on a repo we don't own",
    )
    decision = engine.classify(foreign)
    assert decision.verdict.value == "deny"
    with pytest.raises(ApprovalError):
        queue.request(foreign, decision, trace_id="t")
