"""Unit tests for triage application — behind policy, dry-run default (CLAUDE.md §9).

Prove that triage outcomes only reach GitHub through the approval queue and
the execution gate: dry-run performs no mutation, approval is required to
apply, and the rendered content is evidence-bearing and AI-labeled. The
GitHub writer is an in-memory stub; no network.
"""

from __future__ import annotations

from datetime import UTC, datetime

import pytest

from steward.config import Settings
from steward.policy import (
    ApprovalQueue,
    ExecutionGate,
    ExecutionStatus,
    InMemoryAuditLog,
    PolicyViolationError,
)
from steward.triage.apply import (
    AI_GENERATED_LABEL,
    TriageApplier,
    build_triage_comment,
    build_triage_labels,
)
from steward.triage.classify import IssueCategory, TriageDecision
from steward.triage.dedup import DuplicateCandidate, DuplicateReport
from steward.triage.models import IssueState, NormalizedIssue

TARGET = "vivekanjana76/steward-demo"
FIXED_NOW = datetime(2026, 6, 12, 12, 0, 0, tzinfo=UTC)


class StubWriter:
    """Records writes instead of touching GitHub."""

    def __init__(self) -> None:
        self.comments: list[tuple[str, int, str]] = []
        self.labels: list[tuple[str, int, tuple[str, ...]]] = []

    def post_comment(self, repo: str, issue_number: int, body: str) -> None:
        self.comments.append((repo, issue_number, body))

    def add_labels(self, repo: str, issue_number: int, labels: tuple[str, ...]) -> None:
        self.labels.append((repo, issue_number, labels))


def _issue(number: int = 42) -> NormalizedIssue:
    return NormalizedIssue(
        number=number,
        title="App crashes on startup",
        body="Crashes when launched.",
        author="octocat",
        state=IssueState.OPEN,
        labels=(),
        created_at=FIXED_NOW,
        updated_at=FIXED_NOW,
    )


def _decision(*, needs_info: bool = False, signals: tuple[str, ...] = ()) -> TriageDecision:
    return TriageDecision(
        category=IssueCategory.BUG,
        confidence=0.4 if needs_info else 0.92,
        rationale="Stack trace and reproduction steps describe a crash.",
        needs_info=needs_info,
        injection_signals=signals,
    )


def _report(with_candidates: bool = True) -> DuplicateReport:
    candidates = (
        (DuplicateCandidate(issue_number=17, title="Crash on launch", score=0.91),)
        if with_candidates
        else ()
    )
    return DuplicateReport(
        issue_number=42, candidates=candidates, threshold=0.85, embedding_model="voyage-3"
    )


def _settings(**env: str) -> Settings:
    base = {"STEWARD_GITHUB_REPO": TARGET}
    base.update(env)
    return Settings(_env_file=None, **base)  # type: ignore[call-arg]


def _applier(settings: Settings, audit: InMemoryAuditLog) -> TriageApplier:
    queue = ApprovalQueue(audit_log=audit, clock=lambda: FIXED_NOW)
    gate = ExecutionGate(settings=settings, audit_log=audit)
    return TriageApplier(repo=TARGET, engine_queue=queue, gate=gate)


class TestRendering:
    def test_labels_always_include_ai_marker_and_category(self) -> None:
        labels = build_triage_labels(_decision())
        assert AI_GENERATED_LABEL in labels
        assert "type:bug" in labels

    def test_needs_info_label_added_when_low_confidence(self) -> None:
        assert "status:needs-info" in build_triage_labels(_decision(needs_info=True))
        assert "status:needs-info" not in build_triage_labels(_decision())

    def test_duplicate_label_only_with_evidence(self) -> None:
        assert "status:possible-duplicate" in build_triage_labels(_decision(), _report())
        assert "status:possible-duplicate" not in build_triage_labels(
            _decision(), _report(with_candidates=False)
        )

    def test_comment_is_ai_labeled_and_carries_classification(self) -> None:
        body = build_triage_comment(_issue(), _decision())
        assert "generated by Steward" in body
        assert "`bug`" in body
        assert "0.92" in body

    def test_comment_cites_duplicates_with_score_and_link(self) -> None:
        body = build_triage_comment(_issue(), _decision(), _report())
        assert "#17" in body
        assert "0.910" in body
        assert "voyage-3" in body

    def test_comment_omits_duplicate_section_without_evidence(self) -> None:
        body = build_triage_comment(_issue(), _decision(), _report(with_candidates=False))
        assert "Possible duplicates" not in body

    def test_comment_surfaces_injection_signals(self) -> None:
        body = build_triage_comment(_issue(), _decision(signals=("instruction-override",)))
        assert "instruction-override" in body


class TestProposal:
    def test_propose_queues_two_pending_approvals(self) -> None:
        audit = InMemoryAuditLog(clock=lambda: FIXED_NOW)
        applier = _applier(_settings(), audit)
        proposal = applier.propose(_issue(), _decision(), trace_id="t")
        assert len(proposal.approvals) == 2
        assert all(a.status.value == "pending" for a in proposal.approvals)
        # Both requests were audited with the trace id.
        assert [r.trace_id for r in audit.records()] == ["t", "t"]

    def test_propose_mutates_nothing(self) -> None:
        audit = InMemoryAuditLog(clock=lambda: FIXED_NOW)
        applier = _applier(_settings(), audit)
        applier.propose(_issue(), _decision(), trace_id="t")
        assert all(not r.executed for r in audit.records())


class TestApply:
    def test_dry_run_default_never_calls_the_writer(self) -> None:
        audit = InMemoryAuditLog(clock=lambda: FIXED_NOW)
        applier = _applier(_settings(), audit)
        queue_proposal = applier.propose(_issue(), _decision(), trace_id="t")
        queue = applier._queue
        writer = StubWriter()
        for pending in queue_proposal.approvals:
            approved = queue.approve(pending.approval_id, by="vivek")
            result = applier.apply(approved, writer, trace_id="t")
            assert result.status is ExecutionStatus.DRY_RUN
        assert writer.comments == []
        assert writer.labels == []
        # The intended changes are still audit-logged.
        dry_runs = [r for r in audit.records() if r.dry_run and not r.executed]
        assert len(dry_runs) >= 2

    def test_unapproved_action_cannot_be_applied(self) -> None:
        audit = InMemoryAuditLog(clock=lambda: FIXED_NOW)
        applier = _applier(_settings(), audit)
        proposal = applier.propose(_issue(), _decision(), trace_id="t")
        queue = applier._queue
        rejected = queue.reject(proposal.approvals[0].approval_id, by="vivek")
        from steward.policy import ApprovedAction

        forged = ApprovedAction.model_construct(
            action=proposal.comment_action,
            decision=proposal.approvals[0].decision,
            approval=rejected,
        )
        with pytest.raises(PolicyViolationError):
            applier.apply(forged, StubWriter(), trace_id="t")

    def test_live_apply_writes_comment_and_labels(self) -> None:
        audit = InMemoryAuditLog(clock=lambda: FIXED_NOW)
        settings = _settings(
            STEWARD_DRY_RUN="false",
            STEWARD_LIVE_ACTIONS="post_issue_comment,apply_labels",
        )
        applier = _applier(settings, audit)
        proposal = applier.propose(_issue(), _decision(), _report(), trace_id="t")
        queue = applier._queue
        writer = StubWriter()
        for pending in proposal.approvals:
            approved = queue.approve(pending.approval_id, by="vivek")
            result = applier.apply(approved, writer, trace_id="t")
            assert result.status is ExecutionStatus.EXECUTED

        assert len(writer.comments) == 1
        repo, number, body = writer.comments[0]
        assert (repo, number) == (TARGET, 42)
        assert "generated by Steward" in body

        assert len(writer.labels) == 1
        _, _, labels = writer.labels[0]
        assert AI_GENERATED_LABEL in labels
        assert "status:possible-duplicate" in labels
