"""Open a DRAFT pull request for a verified fix — gated, labeled, audited.

This is Steward's most consequential world-mutating step, so it runs entirely
inside the trust machinery (CLAUDE.md §1/§5/§6):

* The act of opening the PR is a **greylist** ``OPEN_DRAFT_PR`` action — it is
  classified by the policy engine, **queued for human approval**, and only ever
  executed through the :class:`~steward.policy.execute.ExecutionGate`, which is
  **dry-run by default**. Nothing reaches GitHub until a human approves *and*
  the action is explicitly opted in live.
* The PR is always a **draft**, linked to the issue (``Closes #NN``), and clearly
  **labeled AI-generated** (an ``ai-generated`` label plus a banner in the body),
  carrying its grounding evidence — the reproduction and the passing proof test.
* Steward **never targets a repo it does not own**: the action's repo is the
  configured target, and the policy engine denies anything else, so an
  off-target PR can't even be queued.

This implements the graph's
:class:`~steward.graph.capabilities.PullRequestOpener` seam: ``open_draft``
*proposes* the PR (queues it for approval) and returns the planned draft;
:meth:`DraftPullRequestOpener.execute_approved` performs the live open once a
human has approved.
"""

from __future__ import annotations

import re
from typing import Protocol

from pydantic import BaseModel

from steward.graph.state import GraphState, OpenedPR
from steward.policy.approvals import ApprovalQueue, ApprovedAction
from steward.policy.engine import Action, ActionKind, PolicyEngine
from steward.policy.execute import ExecutionGate, ExecutionStatus

AI_GENERATED_LABEL = "ai-generated"
DEFAULT_BASE_BRANCH = "main"

_SLUG_RE = re.compile(r"[^a-z0-9]+")


class PullRequestRef(BaseModel):
    """The reference GitHub returns for a created pull request."""

    number: int
    url: str


class GitHubClient(Protocol):
    """The side-effecting GitHub surface the opener needs (mocked in tests).

    Both methods mutate the world and are therefore only ever called on the
    gate's live path, never during a dry-run.
    """

    def create_draft_pull_request(
        self, *, repo: str, head: str, base: str, title: str, body: str
    ) -> PullRequestRef: ...

    def add_labels(self, *, repo: str, number: int, labels: list[str]) -> None: ...


def branch_name(issue_number: int, title: str) -> str:
    """Compute the conventional fix branch name, ``fix/issue-NN-slug``."""
    slug = _SLUG_RE.sub("-", title.lower()).strip("-")[:40].strip("-")
    return f"fix/issue-{issue_number}-{slug}" if slug else f"fix/issue-{issue_number}"


def render_pr_body(state: GraphState) -> str:
    """Render the PR body: AI-generated banner, the issue link, and the evidence.

    The body is grounded — it cites the reproduction and the passing proof test
    rather than asserting a fix bare (CLAUDE.md §1).
    """
    issue = state.issue
    patch = state.patch
    repro = state.repro
    result = state.test_result
    summary = (patch.rationale if patch and patch.rationale else state.hypothesis) or "a fix"
    proof_path = patch.proof_test_path if patch else "the proof test"
    if result is not None:
        evidence = (
            f"- Proof test `{proof_path}`: **failed on the unpatched repo, passed after the "
            f"fix** (sandbox run, exit {result.exit_code}, {result.duration_s:.2f}s)."
        )
    else:
        evidence = f"- Proof test `{proof_path}`: pending."
    repro_line = f"- Reproduction: {repro.summary}" if repro else "- Reproduction: n/a"

    return (
        f"Closes #{issue.number}\n\n"
        "> 🤖 **This pull request was generated by Steward (AI).** It is a draft; "
        "a human maintainer must review and merge it. Steward never merges.\n\n"
        f"**What:** {summary}\n\n"
        "**Evidence (grounded — CLAUDE.md §1):**\n"
        f"{repro_line}\n"
        f"{evidence}\n"
        f"- Trace: `{state.trace_id}`\n"
    )


class DraftPullRequestOpener:
    """Proposes and (on approval) opens the draft PR for a verified fix.

    ``engine``/``queue``/``gate`` are the policy machinery; ``github`` is the
    side-effecting client used only on the live path. ``base`` is the branch the
    PR targets.
    """

    def __init__(
        self,
        *,
        engine: PolicyEngine,
        queue: ApprovalQueue,
        gate: ExecutionGate,
        github: GitHubClient,
        base: str = DEFAULT_BASE_BRANCH,
    ) -> None:
        self._engine = engine
        self._queue = queue
        self._gate = gate
        self._github = github
        self._base = base

    def open_draft(self, state: GraphState) -> OpenedPR:
        """Propose the draft PR: classify, queue for approval, return the plan.

        Returns the *planned* draft (no number/url yet). The PR is opened for
        real only after a human approves, via :meth:`execute_approved` — honoring
        dry-run-by-default and human-in-the-loop (CLAUDE.md §5/§6).
        """
        action = self._build_action(state)
        decision = self._engine.classify(action)
        self._queue.request(action, decision, trace_id=state.trace_id)
        return OpenedPR(
            branch=str(action.detail["branch"]),
            title=str(action.detail["title"]),
            draft=True,
        )

    def execute_approved(self, approved: ApprovedAction, *, trace_id: str) -> OpenedPR:
        """Open the PR for an approved action through the gate (dry-run-safe).

        On the dry-run path no GitHub call is made and the planned draft is
        returned; on the live path the draft PR is created and the
        ``ai-generated`` label applied, and the real number/url are returned.
        Every outcome is audited by the gate.
        """
        action = approved.action
        result = self._gate.execute(approved, self._executor, trace_id=trace_id)
        detail = action.detail
        if result.status is ExecutionStatus.DRY_RUN or not isinstance(
            result.output, PullRequestRef
        ):
            return OpenedPR(branch=str(detail["branch"]), title=str(detail["title"]), draft=True)
        ref = result.output
        return OpenedPR(
            branch=str(detail["branch"]),
            title=str(detail["title"]),
            draft=True,
            number=ref.number,
            url=ref.url,
        )

    def _build_action(self, state: GraphState) -> Action:
        issue = state.issue
        branch = branch_name(issue.number, issue.title)
        title = f"fix: {issue.title} (#{issue.number})"
        body = render_pr_body(state)
        return Action(
            kind=ActionKind.OPEN_DRAFT_PR,
            repo=self._engine.target_repo,
            summary=f"Open draft PR for #{issue.number} from {branch}",
            detail={
                "issue": issue.number,
                "branch": branch,
                "base": self._base,
                "title": title,
                "body": body,
            },
        )

    def _executor(self, action: Action) -> PullRequestRef:
        detail = action.detail
        ref = self._github.create_draft_pull_request(
            repo=action.repo,
            head=str(detail["branch"]),
            base=str(detail["base"]),
            title=str(detail["title"]),
            body=str(detail["body"]),
        )
        self._github.add_labels(repo=action.repo, number=ref.number, labels=[AI_GENERATED_LABEL])
        return ref
