"""Apply triage outcomes to GitHub — behind the policy engine, dry-run first.

Turning a :class:`~steward.triage.classify.TriageDecision` (and an optional
:class:`~steward.triage.dedup.DuplicateReport`) into a comment and labels on
the real issue is Steward's first world-mutating capability, so the full
trust machinery applies (CLAUDE.md §5/§6):

* :func:`build_triage_comment` / :func:`build_triage_labels` are **pure**:
  they render the proposed mutation, clearly labeled as AI-generated and
  carrying only grounded evidence (the classifier's confidence + rationale,
  duplicate candidates with linked issue numbers and scores — never an
  unsupported claim).
* :class:`TriageApplier` proposes the mutation as greylist
  :class:`~steward.policy.engine.Action`s through the
  :class:`~steward.policy.approvals.ApprovalQueue` and executes only through
  the :class:`~steward.policy.execute.ExecutionGate` — which means dry-run by
  default, human approval always, and an audit record either way.

The GitHub write itself sits behind the structural :class:`IssueWriter`
protocol so tests inject a stub and the live adapter stays a thin detail.
"""

from __future__ import annotations

from typing import Protocol

from pydantic import BaseModel, ConfigDict

from steward.policy.approvals import ApprovalQueue, ApprovedAction, PendingApproval
from steward.policy.engine import Action, ActionKind, classify
from steward.policy.execute import ExecutionGate, ExecutionResult
from steward.triage.classify import TriageDecision
from steward.triage.dedup import DuplicateReport
from steward.triage.models import NormalizedIssue

# Every piece of Steward-authored content is labeled as AI-generated
# (CLAUDE.md §5) — both in the comment text and as an issue label.
AI_GENERATED_LABEL = "ai-generated"
AI_DISCLOSURE = "*This triage comment was generated by Steward, an AI maintainer assistant.*"

DUPLICATE_LABEL = "status:possible-duplicate"


class TriageProposal(BaseModel):
    """The pair of greylist actions one triage outcome proposes."""

    model_config = ConfigDict(frozen=True)

    comment_action: Action
    labels_action: Action
    approvals: tuple[PendingApproval, ...]


class IssueWriter(Protocol):
    """The slice of GitHub write surface triage application needs.

    Structural on purpose: tests inject an in-memory stub; the live adapter
    wraps the GitHub API and is exercised against the demo repo only.
    """

    def post_comment(self, repo: str, issue_number: int, body: str) -> None:
        """Create a comment on the issue."""
        ...

    def add_labels(self, repo: str, issue_number: int, labels: tuple[str, ...]) -> None:
        """Add ``labels`` to the issue (never removes existing labels)."""
        ...


def build_triage_labels(
    decision: TriageDecision, report: DuplicateReport | None = None
) -> tuple[str, ...]:
    """The labels a triage outcome proposes, always including the AI marker."""
    labels: list[str] = [AI_GENERATED_LABEL, f"type:{decision.category.value}"]
    if decision.suggested_label is not None:
        labels.append(decision.suggested_label)
    if report is not None and report.has_duplicates:
        labels.append(DUPLICATE_LABEL)
    return tuple(labels)


def build_triage_comment(
    issue: NormalizedIssue,
    decision: TriageDecision,
    report: DuplicateReport | None = None,
) -> str:
    """Render the triage comment — evidence-bearing and clearly AI-labeled.

    Grounded-or-silent (CLAUDE.md §1): the duplicate section appears only when
    candidates cleared the documented threshold, and each is cited with its
    issue number and similarity score.
    """
    lines = [
        f"**Triage** for #{issue.number}: `{decision.category.value}` "
        f"(confidence {decision.confidence:.2f})",
        "",
        f"> {decision.rationale}",
    ]
    if decision.needs_info:
        lines += [
            "",
            "Confidence is below the documented threshold, so this issue is "
            "routed to `status:needs-info` rather than asserted as a category. "
            "Maintainers: more detail from the reporter would help.",
        ]
    if report is not None and report.has_duplicates:
        lines += [
            "",
            "**Possible duplicates** (cosine similarity, threshold "
            f"{report.threshold:.2f}, model `{report.embedding_model}`):",
        ]
        lines += [
            f"- #{c.issue_number} — {c.title or 'untitled'} (score {c.score:.3f})"
            for c in report.candidates
        ]
    if decision.injection_signals:
        signals = ", ".join(decision.injection_signals)
        lines += [
            "",
            f"⚠️ Ingestion flagged possible prompt-injection content ({signals}); "
            "the text above was treated strictly as data.",
        ]
    lines += ["", "---", AI_DISCLOSURE]
    return "\n".join(lines)


class TriageApplier:
    """Proposes and (once approved) applies triage outcomes via the policy stack.

    ``repo`` must be the configured target repository — anything else is
    denied by the policy engine when the actions are classified.
    """

    def __init__(
        self,
        *,
        repo: str,
        engine_queue: ApprovalQueue,
        gate: ExecutionGate,
    ) -> None:
        self._repo = repo
        self._queue = engine_queue
        self._gate = gate

    def propose(
        self,
        issue: NormalizedIssue,
        decision: TriageDecision,
        report: DuplicateReport | None = None,
        *,
        trace_id: str,
    ) -> TriageProposal:
        """Build the comment + labels actions and queue them for approval.

        Nothing mutates here: the result is a pair of pending approvals, each
        already recorded in the audit log.
        """
        comment_action = Action(
            kind=ActionKind.POST_ISSUE_COMMENT,
            repo=self._repo,
            summary=f"post triage comment on #{issue.number}",
            detail={
                "issue_number": issue.number,
                "body": build_triage_comment(issue, decision, report),
            },
        )
        labels_action = Action(
            kind=ActionKind.APPLY_LABELS,
            repo=self._repo,
            summary=f"apply triage labels to #{issue.number}",
            detail={
                "issue_number": issue.number,
                "labels": list(build_triage_labels(decision, report)),
            },
        )
        approvals = tuple(
            self._queue.request(action, classify(action, target_repo=self._repo), trace_id=trace_id)
            for action in (comment_action, labels_action)
        )
        return TriageProposal(
            comment_action=comment_action,
            labels_action=labels_action,
            approvals=approvals,
        )

    def apply(
        self, approved: ApprovedAction, writer: IssueWriter, *, trace_id: str
    ) -> ExecutionResult:
        """Execute one approved triage action through the gate.

        In dry-run (the default) the writer is never called and an audit
        record describes the intended change; live execution additionally
        requires the per-kind opt-in (CLAUDE.md §5).
        """
        return self._gate.execute(
            approved, lambda action: self._write(action, writer), trace_id=trace_id
        )

    def _write(self, action: Action, writer: IssueWriter) -> None:
        issue_number = int(action.detail["issue_number"])
        if action.kind is ActionKind.POST_ISSUE_COMMENT:
            writer.post_comment(action.repo, issue_number, str(action.detail["body"]))
        elif action.kind is ActionKind.APPLY_LABELS:
            writer.add_labels(
                action.repo, issue_number, tuple(str(s) for s in action.detail["labels"])
            )
        else:  # pragma: no cover - the gate only passes triage kinds here
            raise ValueError(f"unsupported triage action kind: {action.kind}")
